version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - ./create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh

volumes:
  postgres:
